-- Shareable per-race URLs: /race/<slug>
--
-- Slugs are derived from the race name plus the year of its date
-- ("Berlin Marathon" + 2026 -> berlin-marathon-2026) and uniquified with a
-- -2/-3/... suffix.
--
-- The slug is generated by a database trigger rather than in app.js on purpose:
--   * every write path gets a slug, regardless of which client made the write
--     (the app, the SQL editor, a future import script);
--   * de-duplication happens in the same statement that the unique index
--     guards, which an app-side read-then-write cannot guarantee;
--   * app.js needs no change to addRace/updateRace, so an older cached copy of
--     the app keeps working after this migration lands.

alter table public.races add column if not exists slug text;

comment on column public.races.slug is
  'URL-safe identifier used for /race/<slug> share links. Maintained by the races_slug_biu trigger; do not set it from the client.';

-- ---------------------------------------------------------------------------
-- slugify(): lowercase, transliterate common Latin-1 accents, collapse every
-- other run of characters to a single dash, trim dashes. Returns NULL (not '')
-- for input that has no usable characters at all, so callers can coalesce.
-- translate() is used instead of unaccent() to avoid depending on an extension.
-- The two character maps below MUST stay the same length (57): translate()
-- silently *deletes* characters in `from` that have no counterpart in `to`.
-- ---------------------------------------------------------------------------
create or replace function public.slugify(value text)
returns text
language sql
immutable
set search_path = pg_catalog, pg_temp
as $$
  select nullif(
    trim(both '-' from
      regexp_replace(
        lower(
          translate(
            coalesce(value, ''),
            'ÀÁÂÃÄÅÆÇÈÉÊËÌÍÎÏÑÒÓÔÕÖØÙÚÛÜÝàáâãäåæçèéêëìíîïñòóôõöøùúûüýÿ',
            'AAAAAAACEEEEIIIINOOOOOOUUUUYaaaaaaaceeeeiiiinoooooouuuuyy'
          )
        ),
        '[^a-z0-9]+', '-', 'g'
      )
    ),
    ''
  );
$$;

-- ---------------------------------------------------------------------------
-- Trigger: assign races.slug on insert, and re-assign it only when something
-- the slug is derived from actually changed.
-- ---------------------------------------------------------------------------
create or replace function public.races_assign_slug()
returns trigger
language plpgsql
security invoker
set search_path = public, pg_temp
as $$
declare
  base      text;
  candidate text;
  n         integer := 1;
  explicit  boolean := false;
begin
  if tg_op = 'UPDATE' then
    if new.slug is not null and new.slug <> '' and new.slug is distinct from old.slug then
      -- A slug written by hand wins. It still gets normalised and uniquified,
      -- but no year is appended and the name does not overwrite it.
      explicit := true;
    elsif new.slug is not null and new.slug <> ''
      and new.name       is not distinct from old.name
      and new.date       is not distinct from old.date
      and new.event_type is not distinct from old.event_type
    then
      -- Nothing the slug derives from changed. Leave it alone: a slug that
      -- shifts on an unrelated update breaks every link already shared.
      return new;
    end if;
  end if;

  if explicit then
    base := public.slugify(new.slug);
  elsif new.event_type = 'Balance Bolt' then
    -- Balance Bolt races are named by number ("3"), which alone would slug to
    -- "3-2026". Prefix them so the shared link says what it is.
    base := public.slugify('balance-bolt-' || coalesce(new.name, ''));
  else
    base := public.slugify(new.name);
  end if;

  base := coalesce(base, 'race');

  if not explicit and new.date is not null then
    base := base || '-' || to_char(new.date, 'YYYY');
  end if;

  -- SECURITY INVOKER, so this de-duplication SELECT runs as the writing role
  -- (anon) and is filtered by RLS. That is correct while the races policies
  -- allow anonymous reads of every row, which is this app's trust model. If
  -- those policies are ever narrowed, this SELECT could miss an occupied slug —
  -- in which case the unique index below rejects the write rather than
  -- corrupting anything, so the failure is loud.
  candidate := base;
  while exists (
    select 1 from public.races r
    where r.slug = candidate
      and r.id is distinct from new.id
  ) loop
    n := n + 1;
    candidate := base || '-' || n;
  end loop;

  new.slug := candidate;
  return new;
end;
$$;

drop trigger if exists races_slug_biu on public.races;
create trigger races_slug_biu
  before insert or update on public.races
  for each row execute function public.races_assign_slug();

-- ---------------------------------------------------------------------------
-- Backfill, one row per statement.
--
-- A single `update public.races set slug = null` would NOT work: a BEFORE ROW
-- trigger cannot see rows changed earlier by its own statement, so the
-- de-duplication SELECT would miss same-name collisions and the unique index
-- below would then fail. Looping gives each row its own statement and therefore
-- its own snapshot.
-- ---------------------------------------------------------------------------
do $$
declare
  r record;
begin
  for r in select id from public.races order by date, created_at, id loop
    update public.races set slug = null where id = r.id;
  end loop;
end;
$$;

create unique index if not exists races_slug_key on public.races (slug);

alter table public.races alter column slug set not null;

-- slugify() is called from a SECURITY INVOKER trigger, so the writing role
-- needs EXECUTE. New functions grant EXECUTE to PUBLIC by default, which
-- already covers this; the explicit grant is insurance against a project that
-- has revoked the default. Guarded so the migration still runs on a plain
-- Postgres without Supabase's roles.
do $$
begin
  if exists (select 1 from pg_roles where rolname = 'anon') then
    execute 'grant execute on function public.slugify(text) to anon, authenticated';
  end if;
end;
$$;
